import aligner.bitext_align as aligner


para1 = 'Oh, if I had done nothing simply from laziness! Heavens, how I should have respected myself, then. I should have respected myself because I should at least have been capable of being lazy; there would at least have been one quality, as it were, positive in me, in which I could have believed myself. '
para2 = 'Oh, wenn ich doch nur aus Faulheit untätig wäre. Herrgott, wie würde ich mich dann achten. Ich würde mich gerade deswegen achten, weil ich dann doch fähig wäre, wenigstens faul zu sein; dann besäße ich wenigstens eine gewissermaßen positive Eigenschaft, von der ich dann auch selbst überzeugt sein könnte.'

text1 = 'Oh, if I had done nothing simply from laziness! Heavens, how I should have respected myself, then. I should have respected myself because I should at least have been capable of being lazy; there would at least have been one quality, as it were, positive in me, in which I could have believed myself. Question: What is he? Answer: A sluggard; how very pleasant it would have been to hear that of oneself! It would mean that I was positively defined, it would mean that there was something to say about me. “Sluggard”— why, it is a calling and vocation, it is a career. Do not jest, it is so. I should then be a member of the best club by right, and should find my occupation in continually respecting myself. I knew a gentleman who prided himself all his life on being a connoisseur of Lafitte. He considered this as his positive virtue, and never doubted himself. He died, not simply with a tranquil, but with a triumphant conscience, and he was quite right, too. Then I should have chosen a career for myself, I should have been a sluggard and a glutton, not a simple one, but, for instance, one with sympathies for everything sublime and beautiful. How do you like that? I have long had visions of it. That “sublime and beautiful” weighs heavily on my mind at forty But that is at forty; then — oh, then it would have been different! I should have found for myself a form of activity in keeping with it, to be precise, drinking to the health of everything “sublime and beautiful.” I should have snatched at every opportunity to drop a tear into my glass and then to drain it to all that is “sublime and beautiful.” I should then have turned everything into the sublime and the beautiful; in the nastiest, unquestionable trash, I should have sought out the sublime and the beautiful. I should have exuded tears like a wet sponge. An artist, for instance, paints a picture worthy of Gay. At once I drink to the health of the artist who painted the picture worthy of Gay, because I love all that is “sublime and beautiful.” An author has written AS YOU WILL: at once I drink to the health of “anyone you will” because I love all that is “sublime and beautiful.” I should claim respect for doing so. I should persecute anyone who would not show me respect. I should live at ease, I should die with dignity, why, it is charming, perfectly charming! And what a good round belly I should have grown, what a treble chin I should have established, what a ruby nose I should have coloured for myself, so that everyone would have said, looking at me: “Here is an asset! Here is something real and solid!” And, say what you like, it is very agreeable to hear such remarks about oneself in this negative age.'
text2 = 'Oh, wenn ich doch nur aus Faulheit untätig wäre. Herrgott, wie würde ich mich dann achten. Ich würde mich gerade deswegen achten, weil ich dann doch fähig wäre, wenigstens faul zu sein; dann besäße ich wenigstens eine gewissermaßen positive Eigenschaft, von der ich dann auch selbst überzeugt sein könnte. Frage: Wer ist das? Antwort: ein Faulpelz; aber ich bitte Sie, das hört sich doch äußerst angenehm an, das heißt, man ist definitiv bestimmt, das heißt, es gibt etwas, was sich über mich sagen läßt. »Ein Faulpelz!« – aber das ist doch Titel und Bestimmung, das ist doch eine Karriere, meine Herrschaften. Scherz beiseite, so ist es! Dann bin ich rechtmäßiges Mitglied eines renommierten Vereins und achte mich unablässig. Ich kannte einen Herrn, der sein Leben lang stolz darauf war, sich auf Lafitte-Weine zu verstehen. Er hielt das für einen ausgesprochenen Vorzug und zweifelte nie an sich selbst. Er starb nicht nur mit ruhigem, sondern mit einem triumphierenden Gewissen und war damit vollkommen im Recht. Denn hätte auch ich Karriere gemacht, ich wäre ein Faulpelz und Vielfraß geworden, doch beileibe kein gewöhnlicher, sondern einer mit Sinn für das Schöne und Erhabene. Was halten Sie davon? Ich träumte schon lange davon. Dieses ›Schöne und Erhabene‹ hat mir doch vierzig Jahre lang schwer im Magen gelegen; das sage ich jetzt, mit meinen vierzig Jahren, damals aber – oh, damals wäre alles ganz anders geworden! Damals hätte ich sofort eine entsprechende Tätigkeit gefunden – und zwar: auf das Wohl alles Schönen und Erhabenen zu trinken. Ich hätte jede Gelegenheit ergriffen, zuerst eine Träne in mein Glas fallen zu lassen und es dann auf das Wohl des Schönen und Erhabenen zu leeren. Alles auf der Welt würde ich dann in Schönes und Erhabenes verwandelt und noch im ekelhaftesten, unzweifelhaften Schlamm Schönes und Erhabenes gefunden haben. Ich hätte die Gabe erlangt, Tränen zu vergießen wie ein nasser Schwamm. Der Maler Gay zum Beispiel malt ein Bild – sofort trinke ich auf die Gesundheit des Künstlers Gay, der das Bild gemalt hat, denn ich liebe alles Schöne und Erhabene. Ein Schriftsteller schreibt »wie es euch gefällt«; sofort trinke ich auf das Wohl dessen, »der euch gefällt«, denn ich liebe das Schöne und Erhabene. Achtung würde ich deshalb für mich heischen und jeden verfolgen, der mir nicht Achtung zollt. Ich lebe ruhig, ich sterbe feierlich – das ist ja reizend, wirklich reizend! Und was für einen Schmerbauch hätte ich mir zugelegt, welch dreifaches Doppelkinn! Über eine Schnapsnase würde ich verfügen, bei deren Anblick jeder ausrufen müßte: »Das ist aber ein Plus! Das ist mal wirklich was Positives!« Sagen Sie, was Sie wollen, meine Herrschaften, aber solche Äußerungen klingen doch in unserem negativen Zeitalter außerordentlich angenehm.'

list1, list2 = aligner.master_align(para1, para2, 'en', 'de')

print(list1)
print(list2)