JSON_PATH = 'json/books.json'

XSD_PATH = 'schema/book.xsd'

CSV_FILE = 'books_data.csv'

DATA_FOLDER = '/data/'

TRANSLATE_ENV_VAR = 'GOOGLE_APPLICATION_CREDENTIALS'

MYSQL_PASS_ENV_VAR = 'MYSQL_PASSWORD'

MYSQL_HOST_ENV_VAR = 'MYSQL_HOST'

WARNING = '\033[91m'
END = '\033[0m'

BLUE = '\033[94m'
GREEN = '\033[92m'